# Generated by Django 5.1.4 on 2025-01-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название сервера'),
        ),
    ]
